### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by Kassandra-QA** [Kassandra-QA/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Oleksandra-Pidchibii** [comment]
A long time ago, in a galaxy far, far away, was a young girl who wanted to realize herself in the IT-sphere. First of all, she searched for information on Google and asked her friends-programmers how to target her goal. Thanks to advice from google and her friends, she decided to start her carrier in QA  because she had some technical background, good root cause analysis, and quick-learn skills.
